/*
Creates and populates a table with accelerometer features generated
by the six feature callers

-- NOTE: Drop the final column (error) because it is usually absent,
--       and absence makes imports error

The template for the accelerometer data table below is generated from
a TSV feature file using <python script name>

Before import: edit the TSV file to be imported, replacing the header line with
the edited version below, where the illegal characters have been removed

# unmodified file header
deviceMotion_tremor_handInLap_right.json.items	recordId	appVersion	phoneInfo	uploadDate	healthCode	externalId	dataGroups	createdOn	createdOnTimeZone	userSharingScope	accel_tremor_handInLap_right.json.items	accel_tremor_handInLap_left.json.items	deviceMotion_tremor_handInLap_left.json.items	accel_tremor_handAtShoulderLength_right.json.items	deviceMotion_tremor_handAtShoulderLength_right.json.items	accel_tremor_handAtShoulderLength_left.json.items	deviceMotion_tremor_handAtShoulderLength_left.json.items	accel_tremor_handToNose_right.json.items	deviceMotion_tremor_handToNose_right.json.items	accel_tremor_handToNose_left.json.items	deviceMotion_tremor_handToNose_left.json.items	momentInDayFormat.json.choiceAnswers	medicationActivityTiming.json.choiceAnswers	skipHand.json.answer	idx	lap_right_file	medicationTime	momentInDay	meanX	sdX	modeX	skewX	kurX	q1X	medianX	q3X	iqrX	rangeX	acfX	zcrX	dfaX	cvX	tkeoX	F0X	P0X	F0FX	P0FX	medianF0FX	sdF0FX	tlagX	meanY	sdY	modeY	skewY	kurY	q1Y	medianY	q3Y	iqrY	rangeY	acfY	zcrY	dfaY	cvY	tkeoY	F0Y	P0Y	F0FY	P0FY	medianF0FY	sdF0FY	tlagY	meanZ	sdZ	modeZ	skewZ	kurZ	q1Z	medianZ	q3Z	iqrZ	rangeZ	acfZ	zcrZ	dfaZ	cvZ	tkeoZ	F0Z	P0Z	F0FZ	P0FZ	medianF0FZ	sdF0FZ	tlagZ	meanAA	sdAA	modeAA	skewAA	kurAA	q1AA	medianAA	q3AA	iqrAA	rangeAA	acfAA	zcrAA	dfaAA	cvAA	tkeoAA	F0AA	P0AA	F0FAA	P0FAA	medianF0FAA	sdF0FAA	tlagAA	meanAJ	sdAJ	modeAJ	skewAJ	kurAJ	q1AJ	medianAJ	q3AJ	iqrAJ	rangeAJ	acfAJ	zcrAJ	dfaAJ	cvAJ	tkeoAJ	F0AJ	P0AJ	F0FAJ	P0FAJ	medianF0FAJ	sdF0FAJ	tlagAJ	corXY	corXZ	corYZ	error

# edited file header row (removing illegal chars for column names)
# edit input TSV file to use this
#
deviceMotion_tremor_handInLap_right_json_items	recordId	appVersion	phoneInfo	uploadDate	healthCode	externalId	dataGroups	createdOn	createdOnTimeZone	userSharingScope	accel_tremor_handInLap_right_json_items	accel_tremor_handInLap_left_json_items	deviceMotion_tremor_handInLap_left_json_items	accel_tremor_handAtShoulderLength_right_json_items	deviceMotion_tremor_handAtShoulderLength_right_json_items	accel_tremor_handAtShoulderLength_left_json_items	deviceMotion_tremor_handAtShoulderLength_left_json_items	accel_tremor_handToNose_right_json_items	deviceMotion_tremor_handToNose_right_json_items	accel_tremor_handToNose_left_json_items	deviceMotion_tremor_handToNose_left_json_items	momentInDayFormat_json_choiceAnswers	medicationActivityTiming_json_choiceAnswers	skipHand_json_answer	idx	lap_right_file	medicationTime	momentInDay	meanX	sdX	modeX	skewX	kurX	q1X	medianX	q3X	iqrX	rangeX	acfX	zcrX	dfaX	cvX	tkeoX	F0X	P0X	F0FX	P0FX	medianF0FX	sdF0FX	tlagX	meanY	sdY	modeY	skewY	kurY	q1Y	medianY	q3Y	iqrY	rangeY	acfY	zcrY	dfaY	cvY	tkeoY	F0Y	P0Y	F0FY	P0FY	medianF0FY	sdF0FY	tlagY	meanZ	sdZ	modeZ	skewZ	kurZ	q1Z	medianZ	q3Z	iqrZ	rangeZ	acfZ	zcrZ	dfaZ	cvZ	tkeoZ	F0Z	P0Z	F0FZ	P0FZ	medianF0FZ	sdF0FZ	tlagZ	meanAA	sdAA	modeAA	skewAA	kurAA	q1AA	medianAA	q3AA	iqrAA	rangeAA	acfAA	zcrAA	dfaAA	cvAA	tkeoAA	F0AA	P0AA	F0FAA	P0FAA	medianF0FAA	sdF0FAA	tlagAA	meanAJ	sdAJ	modeAJ	skewAJ	kurAJ	q1AJ	medianAJ	q3AJ	iqrAJ	rangeAJ	acfAJ	zcrAJ	dfaAJ	cvAJ	tkeoAJ	F0AJ	P0AJ	F0FAJ	P0FAJ	medianF0FAJ	sdF0FAJ	tlagAJ	corXY	corXZ	corYZ	error
*/

DROP TABLE acc_1;

CREATE TABLE acc_1
(
   deviceMotion_tremor_handInLap_right_json_items varchar(200),
   recordId varchar(200),
   appVersion varchar(200),
   phoneInfo varchar(200),
   uploadDate date,
   healthCode varchar(200),
   externalId varchar(200),
   dataGroups varchar(200),
   createdOn timestamp,
   createdOnTimeZone varchar(200),
   userSharingScope varchar(200),
   accel_tremor_handInLap_right_json_items varchar(200),
   accel_tremor_handInLap_left_json_items varchar(200),
   deviceMotion_tremor_handInLap_left_json_items varchar(200),
   accel_tremor_handAtShoulderLength_right_json_items varchar(200),
   deviceMotion_tremor_handAtShoulderLength_right_json_items varchar(200),
   accel_tremor_handAtShoulderLength_left_json_items varchar(200),
   deviceMotion_tremor_handAtShoulderLength_left_json_items varchar(200),
   accel_tremor_handToNose_right_json_items varchar(200),
   deviceMotion_tremor_handToNose_right_json_items varchar(200),
   accel_tremor_handToNose_left_json_items varchar(200),
   deviceMotion_tremor_handToNose_left_json_items varchar(200),
   momentInDayFormat_json_choiceAnswers varchar(200),
   medicationActivityTiming_json_choiceAnswers varchar(200),
   skipHand_json_answer varchar(200),
   idx varchar(200),
   lap_right_file varchar(200),
   medicationTime varchar(200),
   momentInDay varchar(200),
   meanX double precision,
   sdX double precision,
   modeX double precision,
   skewX double precision,
   kurX double precision,
   q1X double precision,
   medianX double precision,
   q3X double precision,
   iqrX double precision,
   rangeX double precision,
   acfX double precision,
   zcrX double precision,
   dfaX double precision,
   cvX double precision,
   tkeoX double precision,
   F0X double precision,
   P0X double precision,
   F0FX double precision,
   P0FX double precision,
   medianF0FX double precision,
   sdF0FX double precision,
   tlagX double precision,
   meanY double precision,
   sdY double precision,
   modeY double precision,
   skewY double precision,
   kurY double precision,
   q1Y double precision,
   medianY double precision,
   q3Y double precision,
   iqrY double precision,
   rangeY double precision,
   acfY double precision,
   zcrY double precision,
   dfaY double precision,
   cvY double precision,
   tkeoY double precision,
   F0Y double precision,
   P0Y double precision,
   F0FY double precision,
   P0FY double precision,
   medianF0FY double precision,
   sdF0FY double precision,
   tlagY double precision,
   meanZ double precision,
   sdZ double precision,
   modeZ double precision,
   skewZ double precision,
   kurZ double precision,
   q1Z double precision,
   medianZ double precision,
   q3Z double precision,
   iqrZ double precision,
   rangeZ double precision,
   acfZ double precision,
   zcrZ double precision,
   dfaZ double precision,
   cvZ double precision,
   tkeoZ double precision,
   F0Z double precision,
   P0Z double precision,
   F0FZ double precision,
   P0FZ double precision,
   medianF0FZ double precision,
   sdF0FZ double precision,
   tlagZ double precision,
   meanAA double precision,
   sdAA double precision,
   modeAA double precision,
   skewAA double precision,
   kurAA double precision,
   q1AA double precision,
   medianAA double precision,
   q3AA double precision,
   iqrAA double precision,
   rangeAA double precision,
   acfAA double precision,
   zcrAA double precision,
   dfaAA double precision,
   cvAA double precision,
   tkeoAA double precision,
   F0AA double precision,
   P0AA double precision,
   F0FAA double precision,
   P0FAA double precision,
   medianF0FAA double precision,
   sdF0FAA double precision,
   tlagAA double precision,
   meanAJ double precision,
   sdAJ double precision,
   modeAJ double precision,
   skewAJ double precision,
   kurAJ double precision,
   q1AJ double precision,
   medianAJ double precision,
   q3AJ double precision,
   iqrAJ double precision,
   rangeAJ double precision,
   acfAJ double precision,
   zcrAJ double precision,
   dfaAJ double precision,
   cvAJ double precision,
   tkeoAJ double precision,
   F0AJ double precision,
   P0AJ double precision,
   F0FAJ double precision,
   P0FAJ double precision,
   medianF0FAJ double precision,
   sdF0FAJ double precision,
   tlagAJ double precision,
   corXY double precision,
   corXZ double precision,
   corYZ double precision
);

-- populate with feature data
-- NOTE specifying HEADERS does *NOT* mean data items are ignored if
-- they are under a column not to import - the job still errors.
-- use Python script <name here> to preprocess and strip the error field
COPY acc_1 FROM '/Users/sjm/Git/DS/Week10/tdata/output_tsv.tsv' WITH (FORMAT CSV, DELIMITER E'\t', HEADER);
